# Generated by Django 3.2.24 on 2024-03-16 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_item', models.CharField(max_length=20, verbose_name='Codigo de item')),
                ('nom_item', models.CharField(max_length=30, verbose_name='Nombre de Item')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='FechaHoraModificacionSubitem')),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo'), ('suspendido', 'suspendido')], max_length=15, verbose_name='Estado de Menu')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='sub_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_subitem', models.CharField(max_length=20, verbose_name='Codigo de Sub-Item')),
                ('nom_SubItem', models.CharField(max_length=30, verbose_name='Nombre de Sub-Item')),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo'), ('suspendido', 'suspendido')], max_length=15, verbose_name='Estado de Sub-Item')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='FechaHoraModificacionSubitem')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.item')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userCreacionSubItem', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermodSubitem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='menu_principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_menu', models.CharField(max_length=20, verbose_name='Codigo de menu')),
                ('nom_menu', models.CharField(max_length=30, verbose_name='Nombre de menu')),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo'), ('suspendido', 'suspendido')], max_length=15, verbose_name='Estado de Menu')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userCreacionMenu_principal', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermodMenu_principal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'menu principal',
                'verbose_name_plural': 'menu principal',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='id_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu_principal'),
        ),
        migrations.AddField(
            model_name='item',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userCreacionItem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermodItem', to=settings.AUTH_USER_MODEL),
        ),
    ]
